name: Maven CI/CD

on:
 push:
    branches: [ master ]
 workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
